version: '3'
services:
  service-proxy:
    image: bobcrutchley/hidden-service-proxy
    build: ./service-proxy
    environment:
    - HIDDEN_SERVICE_HOST=hidden-service
    - HIDDEN_SERVICE_PORT=80
    depends_on:
    - hidden-service
  hidden-service:
    image: nginx:latest

